// Copies the compiled ABIs from ../contracts/out into src/abi as typed TS constants.
// Run after `forge build`:  npm run abi
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const out = join(root, "..", "contracts", "out");
const dest = join(root, "src", "abi");
mkdirSync(dest, { recursive: true });

for (const [file, name] of [
  ["RWAToken.sol/RWAToken.json", "rwaTokenAbi"],
  ["RWATokenFactory.sol/RWATokenFactory.json", "rwaTokenFactoryAbi"],
]) {
  const { abi } = JSON.parse(readFileSync(join(out, file), "utf8"));
  const ts = `// Auto-generated by scripts/export-abi.mjs — do not edit.\nexport const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n`;
  writeFileSync(join(dest, `${name}.ts`), ts);
  console.log(`wrote src/abi/${name}.ts`);
}
